# Configuration file for filepaths for saving, reading data..etc
# For simplicity and consistency, only full paths should be specified

# directory to store logfiles
logfiledir: "/Users/PeteBarry/Documents/AnalysisCode/multitone/readout_new/testing/logfiles"

# directory to store process-id files for daemons
pidfiledir: "/var/run/roachreadout/"

# main directory that will be used to save data
savedatadir: "/Users/PeteBarry/Documents/AnalysisCode/multitone/readout_new/testing/run/"

# directory to place any live file or RAM disk storage (e.g. last sweep data, live streaming data)
livefiledir: "/mnt/roachreadout/"
